version: '3.8'

services:
  proxy:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      assistant:
        condition: service_started

  # First we need top train the assistant.
  assistant_training:
    image: europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.9.3
    volumes:
      - .:/app
    command:
      - 'train'
    env_file:
      - .env
    user: root

  # Run Rasa Pro with the inspector.
  assistant:
    image: europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.9.3
    volumes:
      - .:/app
    command:
      - 'inspect'
      - '--debug'
      - '--cors "*"'
    ports:
      - '5005'
    env_file:
      - .env
    depends_on:
      assistant_training:
        condition: service_completed_successfully
    user: root

  tracker_store:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: rasa
      POSTGRES_USER: rasa
      POSTGRES_PASSWORD: rasa
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local